version: '3'
services:

  # PHP Service
  php:
    build:
      context: .docker
      dockerfile: php.Dockerfile
    container_name: ${APP_NAME:?err}-php
    volumes:
      - '.:/var/www/html'
      - '.docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME:?err}-nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'php'
    volumes:
      - '.:/var/www/html'
      - '.docker/config/nginx:/etc/nginx/conf.d'

  mysql:
    image: mysql:5.7
    container_name: ${APP_NAME:?err}-mysql
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?err}
      MYSQL_DATABASE: ${DB_DATABASE?err}

volumes:
  mysqldata:
    driver: 'local'

